// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI17JJtymnZYi5IqUIKaqVD2UCvG0_Sic',
    appId: '1:230567985409:web:6ccbb56f9b78b1f1d1db00',
    messagingSenderId: '230567985409',
    projectId: 'infinity-670ac',
    authDomain: 'infinity-670ac.firebaseapp.com',
    storageBucket: 'infinity-670ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkSHuIm4yhiu6I6T7FPD4V5K6A_6JYiyE',
    appId: '1:230567985409:android:a1b99ece6f81fa5bd1db00',
    messagingSenderId: '230567985409',
    projectId: 'infinity-670ac',
    storageBucket: 'infinity-670ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUhvdW7AtoTSVG9I6YjI-5qnNzxPnjfew',
    appId: '1:230567985409:ios:1cb669e388f6f715d1db00',
    messagingSenderId: '230567985409',
    projectId: 'infinity-670ac',
    storageBucket: 'infinity-670ac.appspot.com',
    iosBundleId: 'com.example.fitgram',
  );
}
